---
# ============================================================================
# Install Kubernetes Components on All Master Nodes
# ============================================================================
# Installs and configures:
# - containerd (container runtime)
# - Kubernetes repository
# - kubelet, kubeadm, kubectl
# - Helm
#
# Tags: install, components
# ============================================================================

- name: Install and Configure Production Kubernetes 1.34.1 Cluster
  hosts: k8s_masters
  become: true
  gather_facts: true
  tags:
    - install
    - components

  handlers:
    - name: Restart containerd
      ansible.builtin.systemd:
        name: containerd
        state: restarted
        daemon_reload: true

    - name: Restart kubelet
      ansible.builtin.systemd:
        name: kubelet
        state: restarted
        daemon_reload: true

  pre_tasks:
    - name: Verify Debian 13
      ansible.builtin.assert:
        that:
          - ansible_distribution == "Debian"
          - ansible_distribution_major_version == "13"
        fail_msg: "System must be Debian 13"
        success_msg: "Debian 13 verified"

    - name: Check containerd availability
      ansible.builtin.command: which containerd || command -v containerd
      register: containerd_available
      changed_when: false
      failed_when: false

    - name: Verify containerd is available or will be installed
      ansible.builtin.assert:
        that:
          - containerd_available.rc == 0 or true
        fail_msg: "Checking containerd availability"
        success_msg: "containerd check passed"

  tasks:
    - name: Install Kubernetes prerequisites (ipvsadm, ipset, etc.)
      ansible.builtin.apt:
        name: "{{ k8s_required_packages }}"
        state: present
        update_cache: true
      register: k8s_prereq_install

    - name: Load IPVS kernel modules
      ansible.builtin.command: modprobe {{ item }}
      loop: "{{ k8s_kernel_modules }}"
      changed_when: false
      failed_when: false

    - name: Configure containerd
      ansible.builtin.include_role:
        name: containerd-configure

    - name: Setup Kubernetes repository
      ansible.builtin.include_role:
        name: kubernetes-repository

    - name: Install Kubernetes components
      ansible.builtin.include_role:
        name: kubernetes-install

    - name: Install Helm
      ansible.builtin.include_role:
        name: helm-install

  post_tasks:
    - name: Display installation summary
      ansible.builtin.debug:
        msg:
          - "=========================================="
          - "Kubernetes components installed on {{ inventory_hostname }}"
          - "Kubernetes version: {{ k8s_version }}"
          - "Containerd: {{ containerd_version }}"
          - "Helm: {{ helm_version }}"
          - "=========================================="
